---
- name: Download Tomcat9 from tomcat.apache.org
  hosts: devops
  tasks:
    - name: Create a Directory /opt/tomcat9
      file:
        path: /opt/tomcat9
        state: directory
        mode: 0755
    - name: Download the Tomcat checksum
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz.sha512
        dest: /opt/tomcat9/apache-tomcat-9.0.65.tar.gz.sha512
        mode: 0755
        validate_certs: no